name: Conversion Execution
on: [workflow_dispatch]

jobs:
  convert-pack:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Enable default asset cache
        id: cache-default-assets
        uses: actions/cache@v3
        with:
          path: /home/runner/work/java2bedrock.sh/java2bedrock.sh/staging/default_assets.zip
          key: ${{ runner.os }}-${{ secrets.DEFAULT_ASSETS_VERSION }}
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Install dependencies
        run: |
          sudo apt-get install -y moreutils zip
          yarn global add spritesheet-js
      - name: Convert Pack
        id: convert-pack
        continue-on-error: false
        env: 
          PACK_URL: ${{ secrets.PACK_URL }}
          DEFAULT_PACK_URL: ${{ secrets.DEFAULT_PACK_URL }}
          MERGE_PACK_URL: ${{ secrets.MERGE_PACK_URL }}
          DEFAULT_ASSETS_VERSION: ${{ secrets.DEFAULT_ASSETS_VERSION }}
          BLOCK_MATERIAL: ${{ secrets.BLOCK_MATERIAL }}
          ATTACHABLE_MATERIAL: ${{ secrets.ATTACHABLE_MATERIAL }}
          ARCHIVE_SCRATCH: ${{ secrets.ARCHIVE_SCRATCH }}
        run: |
          mkdir -p staging
          cp converter.sh staging/
          cd staging
          chmod +x converter.sh
          COLUMNS=$COLUMNS-1 curl --no-styled-output -#L -o input_pack.zip "${PACK_URL}"
          MERGE_PACK_FILE="${MERGE_PACK_URL}"
          if [ "${MERGE_PACK_URL}" != "null" ]; then
            COLUMNS=$COLUMNS-1 curl --no-styled-output -#L -o merge_pack.zip "${MERGE_PACK_URL}"
            MERGE_PACK_FILE="merge_pack.zip"
          fi
          ./converter.sh input_pack.zip -w "false" -m ${MERGE_PACK_FILE} -a ${ATTACHABLE_MATERIAL} -b ${BLOCK_MATERIAL} -f ${DEFAULT_PACK_URL} -v ${DEFAULT_ASSETS_VERSION} -s ${ARCHIVE_SCRATCH} -u "true"
      - name: Upload converted pack
        uses: actions/upload-artifact@v3
        with:
          name: Pack Files
          path: |
            staging/target/packaged/geyser_resources.mcpack
            staging/target/packaged/geyser_addon.mcaddon
            staging/target/geyser_mappings.json
            staging/target/scratch_files.zip
            staging/config.json
